export const mlhConfig = {
  id: 'mlh',
  name: 'MLH',
  baseUrl: 'https://mlh.io',
  listingUrl: 'https://mlh.io/seasons/2025/events',
  delayMs: 1000,
  concurrency: 1,
  retryAfterMs: 1500,
  timeoutMs: 20_000,
  enableProxy: false,
  userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',
  headers: { Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' },
  maxPages: 2,
  detailPageLimit: 25,
  crawlType: 'html' as const,
  sourceType: 'mlh' as const,
};
