import { BaseAdapter } from './baseAdapter';
import { parseGenericListingHtml } from './genericEventParser';

export class MeetupAdapter extends BaseAdapter {
  public readonly id = 'meetup';
  public readonly name = 'Meetup';

  constructor() {
    super({
      id: 'meetup',
      name: 'Meetup',
      baseUrl: 'https://www.meetup.com',
      delayMs: 1000,
      concurrency: 1,
      retryAfterMs: 1500,
      timeoutMs: 20_000,
      enableProxy: false,
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',
      headers: { Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' },
      maxPages: 3,
      detailPageLimit: 25,
      crawlType: 'html',
      sourceType: 'generic',
    });
  }

  protected override listingUrls(): string[] {
    return ['https://www.meetup.com/find/?eventType=hackathon'];
  }

  protected override createRawHackathons(payload: unknown): ReturnType<BaseAdapter['createRawHackathons']> {
    return parseGenericListingHtml(payload, 'meetup', {
      baseUrl: 'https://www.meetup.com',
      sourceName: 'Meetup',
      urlPatterns: [/meetup\.com\/[^/]+\/events\/[^/]+/i],
      rejectPatterns: [
        /meetup\.com\/find/i,
        /meetup\.com\/[^/]+\/?$/i,
        /meetup\.com\/[^/]+\/members/i,
        /meetup\.com\/[^/]+\/photos/i,
        /meetup\.com\/[^/]+\/discussions/i,
        /meetup\.com\/[^/]+\/events\/?$/i,
        /meetup\.com\/[^/]+\/events\/past/i,
        /meetup\.com\/[^/]+\/events\/upcoming/i,
        /meetup\.com\/[^/]+\/events\/drafts/i,
        /meetup\.com\/[^/]+\/events\/proposed/i,
        /meetup\.com\/[^/]+\/events\/canceled/i,
        /meetup\.com\/[^/]+\/events\/deleted/i,
        /meetup\.com\/[^/]+\/events\/calendar/i,
        /meetup\.com\/[^/]+\/events\/list/i,
        /meetup\.com\/[^/]+\/events\/grid/i,
        /meetup\.com\/[^/]+\/events\/map/i,
        /meetup\.com\/[^/]+\/about/i,
        /meetup\.com\/[^/]+\/rules/i,
        /meetup\.com\/[^/]+\/leaders/i,
        /meetup\.com\/[^/]+\/organizers/i,
        /meetup\.com\/[^/]+\/sponsors/i,
        /meetup\.com\/[^/]+\/venues/i,
        /meetup\.com\/[^/]+\/topics/i,
        /meetup\.com\/[^/]+\/categories/i,
        /meetup\.com\/[^/]+\/settings/i,
        /meetup\.com\/[^/]+\/manage/i,
        /meetup\.com\/[^/]+\/edit/i,
        /meetup\.com\/[^/]+\/create/i,
        /meetup\.com\/[^/]+\/schedule/i,
        /meetup\.com\/[^/]+\/attendance/i,
        /meetup\.com\/[^/]+\/polls/i,
        /meetup\.com\/[^/]+\/questions/i,
        /meetup\.com\/[^/]+\/announcements/i,
        /meetup\.com\/[^/]+\/messages/i,
        /meetup\.com\/[^/]+\/mailing-list/i,
        /meetup\.com\/[^/]+\/files/i,
        /meetup\.com\/[^/]+\/links/i,
        /meetup\.com\/[^/]+\/tracks/i,
        /meetup\.com\/[^/]+\/pro/i,
        /meetup\.com\/pro/i,
        /meetup\.com\/pricing/i,
        /meetup\.com\/help/i,
        /meetup\.com\/support/i,
        /meetup\.com\/safety/i,
        /meetup\.com\/guidelines/i,
        /meetup\.com\/terms/i,
        /meetup\.com\/privacy/i,
        /meetup\.com\/cookies/i,
        /meetup\.com\/careers/i,
        /meetup\.com\/press/i,
        /meetup\.com\/about/i,
        /meetup\.com\/blog/i,
        /meetup\.com\/developers/i,
        /meetup\.com\/api/i,
        /meetup\.com\/login/i,
        /meetup\.com\/signup/i,
        /meetup\.com\/join/i,
        /meetup\.com\/signin/i,
        /meetup\.com\/logout/i,
        /meetup\.com\/settings/i,
        /meetup\.com\/profile/i,
        /meetup\.com\/notifications/i,
        /meetup\.com\/messages/i,
        /meetup\.com\/saved/i,
        /meetup\.com\/history/i,
        /meetup\.com\/activity/i,
        /meetup\.com\/events\/?$/i,
        /meetup\.com\/groups\/?$/i,
        /meetup\.com\/cities\//i,
        /meetup\.com\/categories\//i,
        /meetup\.com\/topics\//i,
        /meetup\.com\/search/i,
        /meetup\.com\/explore/i,
        /meetup\.com\/discover/i,
        /\.svg$/i,
        /\.png$/i,
        /\.jpg$/i,
        /\.jpeg$/i,
        /\.gif$/i,
        /\.webp$/i,
        /\.js$/i,
        /\.css$/i,
        /\/assets\//i,
        /\/static\//i,
      ],
      maxItems: 12,
    });
  }
}